services:
  chroma:
    image: "chromadb/chroma"
    env_file:
      - .chroma_env
      
  web: 
      build: 
        context: .
        dockerfile: Dockerfile
      image: confluence-voice-ai-chat-beta-2
      container_name: confluence-voice-ai-chat-beta-2
      ports:
        - "5000:5000"

  